// playground/vue3/app.vue
<template>
  <div>
    <h1>Watermark Design Vue3 Playground</h1>
    <Watermark
      v-model="form.visible"
      layout="grid"
      :content="form.content"
      :width="form.width"
      :height="form.height"
      :appendToBody="form.appendToBody"
      :gridLayoutOptions="gridLayoutOptions"
      :advancedStyle="advancedStyle"
    >
      <div style="height: 500px">
        <el-form :model="form" label-width="80px">
          <el-form-item label="Content">
            <el-input v-model="form.content" />
          </el-form-item>
          <el-form-item label="Visible">
            <el-switch v-model="form.visible" />
          </el-form-item>
          <el-form-item label="appendToBody">
            <el-switch v-model="form.appendToBody" />
          </el-form-item>
        </el-form>
      </div>
    </Watermark>
  </div>
</template>
<script lang="ts" setup>
  import { reactive } from 'vue-demi';
  import type { GridLayoutOptions, AdvancedStyleType } from '../../packages/core';
  const form = reactive({
    visible: true,
    appendToBody: false,
    content: 'hello watermark',
    width: 200,
    height: 200,
  });
  const gridLayoutOptions: GridLayoutOptions = {
    rows: 2,
    cols: 2,
    gap: [20, 20],
    matrix: [
      [1, 0],
      [0, 1],
    ],
  };

  const advancedStyle: AdvancedStyleType = {
    type: 'linear',
    colorStops: [
      {
        offset: 0,
        color: 'red',
      },
      {
        offset: 1,
        color: 'blue',
      },
    ],
  };
</script>

// playground/react/app.tsx
import React, { useState, ChangeEvent } from 'react';
import { Watermark } from '../../packages/react/src/main';
import { AdvancedStyleType, GridLayoutOptions } from '../../packages/core/src/main';

function App(): React.JSX.Element {
  const [inputValue, setInputValue] = useState('hello watermark');

  const handleInputChange = (event: ChangeEvent) => {
    setInputValue((event.target as HTMLInputElement).value);
  };

  const gridLayoutOptions: GridLayoutOptions = {
    rows: 2,
    cols: 2,
    gap: [20, 20],
    matrix: [
      [1, 0],
      [0, 1],
    ],
  };

  const advancedStyle: AdvancedStyleType = {
    type: 'linear',
    colorStops: [
      {
        offset: 0,
        color: 'red',
      },
      {
        offset: 1,
        color: 'blue',
      },
    ],
  };

  return (
    <div className="App">
      <input type="text" value={inputValue} onChange={handleInputChange} />
      <Watermark
        width={200}
        height={200}
        content={inputValue}
        layout={'grid'}
        gridLayoutOptions={gridLayoutOptions}
        advancedStyle={advancedStyle}
      >
        <div style={{ height: 400 }}></div>
      </Watermark>
    </div>
  );
}

export default App;
